apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-todo

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: ai-todo-local
    includeSelectors: false
    includeTemplates: true

patches:
  - target:
      kind: Service
      name: api
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: replace
        path: /spec/ports
        value:
          - port: 8082
            targetPort: 3100
            protocol: TCP

configMapGenerator:
  - name: ai-todo-config
    behavior: merge
    envs:
      - .env.local.configs

secretGenerator:
  - name: ai-todo-secrets
    envs:
      - .env.local.secrets

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/xiaolinstar/ai-todo-api
    newName: ghcr.io/xiaolinstar/ai-todo-api
    newTag: latest
