apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-todo

resources:
  - ../../base/db

patches:
  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
