apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-todo

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: api
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports
        value:
          - port: 3100
            targetPort: 3100
            nodePort: 30082
            protocol: TCP
  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-pvc
      spec:
        resources:
          requests:
            storage: 5Gi

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ai-todo-secrets
    envs:
      - .env.production.secrets

images:
  - name: ghcr.io/xiaolinstar/ai-todo-api
    newName: ghcr.io/xiaolinstar/ai-todo-api
    newTag: latest
