apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-todo

resources:
  - ../../base/db

labels:
  - pairs:
      app.kubernetes.io/instance: ai-todo-local
    includeSelectors: false
    includeTemplates: true
