apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app.kubernetes.io/name: postgres-pvc
    app.kubernetes.io/part-of: ai-todo
    app.kubernetes.io/component: db
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
