apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-todo-staging

resources:
  - ../../base/migration

images:
  - name: ghcr.io/xiaolinstar/ai-todo-api
    newName: ghcr.nju.edu.cn/xiaolinstar/ai-todo-api
