apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-todo

resources:
  - ../../base/migration

labels:
  - pairs:
      app.kubernetes.io/instance: ai-todo-local
    includeSelectors: false
    includeTemplates: true

images:
  - name: ghcr.io/xiaolinstar/ai-todo-api
    newName: ghcr.io/xiaolinstar/ai-todo-api
    newTag: latest
